services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "middleware"

  middleware:
    build:
      context: ./middleware/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "loadbalancer"

  loadbalancer:
    build:
      context: ./loadbalancer/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - "back-1"
      - "back-2"
      - "servicios-1"
      - "servicios-2"
      - "inmuebles-1"
      - "inmuebles-2"

  back-1: &back-base
    build:
      context: ./back/
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - "db"

  back-2:
    <<: *back-base

  servicios-1: &servicios-base
    build:
      context: ./servicios/
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - "db"

  servicios-2:
    <<: *servicios-base

  inmuebles-1: &inmuebles-base
    build:
      context: ./inmuebles/
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - "db"

  inmuebles-2: 
    <<: *inmuebles-base

  db:
    image: postgres:18.4-alpine3.24
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

